# Generated by Django 3.2.9 on 2021-11-30 13:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to=accounts.models.cover_photos_upload_path)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_photos_upload_path)),
            ],
        ),
    ]
