# Generated by Django 3.2.9 on 2021-12-08 15:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=300, null=True), blank=True, default=list, size=None),
        ),
    ]
